package com.xinhua.oa.mapper.auto;

import com.xinhua.oa.model.pojo.ProdUser;
import com.xinhua.oa.model.pojo.ProdUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProdUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_user
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    long countByExample(ProdUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_user
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    int deleteByExample(ProdUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_user
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_user
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    int insert(ProdUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_user
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    int insertSelective(ProdUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_user
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    List<ProdUser> selectByExample(ProdUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_user
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    ProdUser selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_user
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    int updateByExampleSelective(@Param("record") ProdUser record, @Param("example") ProdUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_user
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    int updateByExample(@Param("record") ProdUser record, @Param("example") ProdUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_user
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    int updateByPrimaryKeySelective(ProdUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_user
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    int updateByPrimaryKey(ProdUser record);
}