package com.xinhua.oa.model.pojo;

import java.util.Date;

public class ProdUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_user.guid
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    private String guid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_user.username
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_user.password
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_user.realname
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_user.email
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_user.telephone
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_user.sex
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_user.sort
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    private String sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_user.record_state
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    private String recordState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_user.create_user_id
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_user.update_user_id
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_user.update_time
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_user.guid
     *
     * @return the value of prod_user.guid
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_user.guid
     *
     * @param guid the value for prod_user.guid
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    public void setGuid(String guid) {
        this.guid = guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_user.username
     *
     * @return the value of prod_user.username
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_user.username
     *
     * @param username the value for prod_user.username
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_user.password
     *
     * @return the value of prod_user.password
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_user.password
     *
     * @param password the value for prod_user.password
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_user.realname
     *
     * @return the value of prod_user.realname
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_user.realname
     *
     * @param realname the value for prod_user.realname
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    public void setRealname(String realname) {
        this.realname = realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_user.email
     *
     * @return the value of prod_user.email
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_user.email
     *
     * @param email the value for prod_user.email
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_user.telephone
     *
     * @return the value of prod_user.telephone
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_user.telephone
     *
     * @param telephone the value for prod_user.telephone
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_user.sex
     *
     * @return the value of prod_user.sex
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_user.sex
     *
     * @param sex the value for prod_user.sex
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_user.sort
     *
     * @return the value of prod_user.sort
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_user.sort
     *
     * @param sort the value for prod_user.sort
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    public void setSort(String sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_user.record_state
     *
     * @return the value of prod_user.record_state
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    public String getRecordState() {
        return recordState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_user.record_state
     *
     * @param recordState the value for prod_user.record_state
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    public void setRecordState(String recordState) {
        this.recordState = recordState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_user.create_user_id
     *
     * @return the value of prod_user.create_user_id
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_user.create_user_id
     *
     * @param createUserId the value for prod_user.create_user_id
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_user.update_user_id
     *
     * @return the value of prod_user.update_user_id
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_user.update_user_id
     *
     * @param updateUserId the value for prod_user.update_user_id
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_user.update_time
     *
     * @return the value of prod_user.update_time
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_user.update_time
     *
     * @param updateTime the value for prod_user.update_time
     *
     * @mbg.generated Sun Apr 08 14:44:08 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}